### ISSUE TITLE
Doesn't seem to work out on Vercel Deployment

### ISSUE THREAD

**Issue by davidbfrogman** [theogravity/pino-datadog-transport#12] opened 2022-10-10 20:36 UTC
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/7316909/194948545-1cf28bc8-6fff-4720-8297-3f12f3452ea7.png">

Something about being deployed out there doesn't allow pino to find the transport.    It works locally, but I guess something must being going sideways on bundling, or something.

**Comment by theogravity** [comment] 2022-10-10 21:36
What does your config for pino look like?

Pino v7 transports basically launch a webworker to run the transport so lots of things can go wrong

**Comment by theogravity** [comment] 2022-10-10 21:41
Another possible alternative is to do this route:

https://github.com/theogravity/pino-datadog-transport#implementing-the-onerror--ondebug-callback

No need to implement the onerror/ondebug, but at least you're telling pino the exact location of the file for the webworker to load

**Comment by theogravity** [comment] 2022-10-22 21:46
Closing as there hasn't been any feedback.

**Closed as completed by theogravity** 2022-10-22 21:46 UTC

**Comment by aecorredor** [comment] 2023-01-26 04:26
Running into something similar when running on AWS Lambda (bundling with esbuild). 

I initially thought that just doing

`import 'pino-datadog-transport` would do the trick, but it's still not bundled. Any ideas here? The webworker stuff sure sounds like the culprit, but I'm surprised no one else is running into this.

**Comment by theogravity** [comment] 2023-01-26 04:58
> Running into something similar when running on AWS Lambda (bundling with esbuild).
> 
> I initially thought that just doing
> 
> `import 'pino-datadog-transport` would do the trick, but it's still not bundled. Any ideas here? The webworker stuff sure sounds like the culprit, but I'm surprised no one else is running into this.

I've had issues with esbuild as well. It's been many months since my attempts, but I think the problem lies with pathing problems trying to find [the external file](https://github.com/theogravity/pino-datadog-transport#implementing-the-onerror--ondebug-callback) used to implement the transport and so the webworker can't find the file. 

I would think that the problem is very much like `pino-pretty` as the [external file solution came from there](https://github.com/pinojs/pino-pretty#handling-non-serializable-options). There might be better luck asking the devs of pino pretty or searching through their issues.

**Comment by theogravity** [comment] 2023-01-26 05:05
Oh I remember, my attempt was around making `pino-datadog-transport` marked as external using some esbuild plugin unsuccessfully and you'd have to manually move over the package from node_modules to your build dir or something like that.

**Comment by aecorredor** [comment] 2023-01-26 17:11
Using `esbuild-plugin-pino` actually solved my issue. I deploy with Pulumi, so I also had to make sure to include the files in the final bundle using `new pulumi.asset.FileAsset`.

with something like:


```typescript
export const createHandlerAssetArchive = (
  handlerPath: string
): pulumi.asset.AssetArchive => {
  return new pulumi.asset.AssetArchive({
    'index.js': new pulumi.asset.FileAsset(handlerPath),
    'dist/pino-file.js': new pulumi.asset.FileAsset('../dist/pino-file.js'),
    'dist/pino-pipeline-worker.js': new pulumi.asset.FileAsset(
      '../dist/pino-pipeline-worker.js'
    ),
    'dist/pino-worker.js': new pulumi.asset.FileAsset('../dist/pino-worker.js'),
    'dist/thread-stream-worker.js': new pulumi.asset.FileAsset(
      '../dist/thread-stream-worker.js'
    ),
    'dist/pino-datadog-transport.js': new pulumi.asset.FileAsset(
      '../dist/pino-datadog-transport.js'
    ),
  });
};
```

EDIT: Make sure that whatever your `outdir` is in `esbuild` also matches the folder prefix for the pino bundled files.

**Comment by theogravity** [comment] 2023-01-26 20:13
> Using `esbuild-plugin-pino` actually solved my issue. I deploy with Pulumi, so I also had to make sure to include the files in the final bundle using `new pulumi.asset.FileAsset`.
> 
> with something like:
> 
> ```ts
> export const createHandlerAssetArchive = (
>   handlerPath: string
> ): pulumi.asset.AssetArchive => {
>   return new pulumi.asset.AssetArchive({
>     'index.js': new pulumi.asset.FileAsset(handlerPath),
>     'pino-file.js': new pulumi.asset.FileAsset('../dist/pino-file.js'),
>     'pino-pipeline-worker.js': new pulumi.asset.FileAsset(
>       '../dist/pino-pipeline-worker.js'
>     ),
>     'pino-worker.js': new pulumi.asset.FileAsset('../dist/pino-worker.js'),
>     'thread-stream-worker.js': new pulumi.asset.FileAsset(
>       '../dist/thread-stream-worker.js'
>     ),
>     'pino-datadog-transport.js': new pulumi.asset.FileAsset(
>       '../dist/pino-datadog-transport.js'
>     ),
>   });
> };
> ```

Glad to hear and thanks for the sample!
